jokeshare/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  get 'jokes/new', to: 'jokes#new', as: 'new_joke'
  post 'jokes/', to: 'jokes#create'
  get 'jokes/OSJokes', to: 'jokes#OSJokes', as: 'os'
  get 'jokes/NetworkingJokes', to: 'jokes#NetworkingJokes', as: 'networking'
  get 'jokes/GeneralJokes', to: 'jokes#GeneralJokes', as: 'general'
  mount Commontator::Engine => '/commontator'
  put "like", to: "jokes#upvote"

  get 'courses/jokes', to: 'courses#jokes', as: 'course_jokes'

  get 'courses/new', to: 'courses#new', as: 'new_course'
  post 'courses/', to: 'courses#create'

end

jokeshare/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :joke
end

jokeshare/app/models/course.rb
class Course < ActiveRecord::Base
	has_many :jokes
	validates_presence_of :subject, :image
	validates_uniqueness_of :subject, :case_sensitive => false
end

jokeshare/app/models/joke.rb
class Joke < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
	has_many :comment
	acts_as_commontable
	acts_as_votable
	validates_presence_of :content, :jokeclass
	def score
  		self.get_upvotes.size
  	end
end

jokeshare/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :name
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :comment
	has_one :joke
	acts_as_commontator
end

jokeshare/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :name) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me, :name) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

jokeshare/app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def new
		@course = Course.new
		render :new
	end

	def create
		subject = params[:course][:subject]
		image = params[:course][:image]
		course = Course.new
		course.subject = subject
		course.image = image
		if(course.valid?)
			course.save
			redirect_to root_path
		else
			flash[:error] = course.errors.first.to_sentence
			new
		end
	end

	def jokes
		@course = Course.find(params[:course_param])
		@jokes = @course.jokes
		render :joke
	end


end

jokeshare/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@courses = Course.all
  end
end

jokeshare/app/controllers/jokes_controller.rb
class JokesController < ApplicationController

	def new
		@joke = Joke.new
		@joke_class = Array.new
		Course.all.each do |course|
			@joke_class.push(course.subject)
		end

		render :new
	end

	def create

		content = params[:joke][:content]
		jokeclass = params[:joke][:jokeclass]
		course = Course.where(:subject => jokeclass)[0]
		course.jokes.create(content: content, jokeclass: jokeclass, user_id: current_user)
		redirect_to root_path
	end
	
	def OSJokes
		@joke = Joke.all
		render :os
	end

	def NetworkingJokes
		@joke = Joke.all
		render :networking 
	end

	def GeneralJokes
		@joke = Joke.all
		render :cs
	end

	def upvote
	  @joke = Joke.find(params[:id])
	  @joke.upvote_by current_user
	  redirect_to :back
	end
	
end

jokeshare/app/helpers/application_helper.rb
module ApplicationHelper
end

jokeshare/app/helpers/courses_helper.rb
module CoursesHelper
end

jokeshare/app/helpers/home_helper.rb
module HomeHelper
end

jokeshare/app/helpers/jokes_helper.rb
module JokesHelper
end

jokeshare/app/views/courses/joke.html.erb
<h1> <%= @course.subject %> Jokes  </h1>

<h3><%=link_to "return home", root_path%></h3>
<%= @jokes.each do |joke|  %>

	
  <div class="jumbotron">
      <div class="container">
		<h3> <%= joke.content %></h3>
  		<%= commontator_thread(joke) %>
  	  	<%=link_to "upvote",{:controller => "jokes", :action => "upvote", :id => joke.id }, method: :put %>
 		 <%= joke.score %>
      </div>
    </div>

<% end %>

jokeshare/app/views/courses/new.html.erb
<div class="newcourse">
<%= flash[:error] %>
<%= simple_form_for @course do |f| %>
  <%= f.input :subject, label: 'Subject of Class Ex. Networking, Operating Systems', :input_html => {:maxlength => 200, :size => 100} %>
  <%= f.input :image, label: 'Paste an html link of an image for the class', :input_html => {:maxlength => 300, :size => 100} %>
  <%= f.button :submit %>
<% end %>
</div>

jokeshare/app/views/home/index.html.erb
<html>

  <head>

    <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" rel="stylesheet">
    
    <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css">
    <link rel="stylesheet" href="main.css">
    
  </head>

  <body>
    <div class="nav">
      <div class="container">
        <ul class="pull-left">
<li> <%= link_to 'Sign Up', new_user_registration_path%>  </li>
<li><%= link_to 'Log In', new_user_session_path%>  </li>
<li> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  </li>
        </ul>
        <ul class="pull-right">


<li>  <%= link_to('Create New Joke', new_joke_path) %>  </li>
<li>  <%= link_to('Create New Course', new_course_path) %>  </li>

        </ul>
      </div>
    </div>

    <div class="jumbotron">
      <div class="container">
        <h1>JokeShare</h1>
        <p>Share topic specific jokes with other CS majors</p>
      </div>
    </div>
    
    <div class="neighborhood-guides">
         <h2>Joke Categories</h2>
         <table>
            
            <tr>
                <% @courses.each do |course| %>
                <td style="text-align:center" class="col-md-3">
                	<h3><%= link_to(course.subject, course_jokes_path(course_param: course.id)) %></h3>
                    <div class="thumbnail">
                      <img src= <%=course.image%> >
                    </div>
                </td>
               <%end%>
            </tr>
         </table>
         
    </div>

  </body>
</html>

jokeshare/app/views/jokes/new.html.erb
<div class="newjoke">
<%= flash[:error] %>
<%= simple_form_for @joke do |f| %>
  <%= f.input :jokeclass, :label => "Joke Class", :collection => @joke_class, :selected => "lead" %>
  <%= f.input :content, label: 'Joke Content', :input_html => {:maxlength => 200, :size => 100}%>
  <%= f.button :submit %>
<% end %>
</div>

jokeshare/app/views/jokes/os.html.erb
<h1>OS Jokes </h1>
<% @joke.each do |joke|  %>

  <% if joke.jokeclass == 'OS' %>
  <div class="jumbotron">
      <div class="container">
		<h3> <%= joke.content %></h3>
  		<%= commontator_thread(joke) %>
  	  	<%=link_to "upvote",{:controller => "jokes", :action => "upvote", :id => joke.id }, method: :put %>
 		 <%= joke.score %>
      </div>
    </div>
  <% end %>
<% end %>

jokeshare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>